<?php
 /** @var $block \Flagbit\Flysystem\Block\Adminhtml\Filesystem\Content\Files */
?>
<?php
$_heigth = 75;
$_width = 100;
$block->getFiles();
?>
<?= $block->getMessages() ?>
<?php if ($block->getFilesCount() > 0): ?>
    <div class="file-head">
        <div class="file-col data-name"><?= $block->escapeHtml(__('Filename')) ?></div>
        <div class="file-col data-size"><?= $block->escapeHtml(__('Size')) ?></div>
        <div class="file-col data-modified-date"><?= $block->escapeHtml(__('Last Modified')) ?></div>
    </div>
    <?php foreach ($block->getFiles() as $file): ?>
        <div data-row="file" class="file-row" id="<?= $block->escapeHtmlAttr($block->getFileId($file)) ?>">
            <div class="file-col data-name"><?= $block->escapeHtml($file['basename']) ?></div>
            <div class="file-col data-size"><?= $block->escapeHtml($block->getFileSize($file)) ?></div>
            <div class="file-col data-modified-date"><?= $block->escapeHtml($block->getLastModified($file)) ?></div>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <div class="empty"><?= $block->escapeHtml(__('No files found')) ?></div>
<?php endif; ?>
