<?php
 /** @var $block \Flagbit\Flysystem\Block\Adminhtml\Filesystem\Content\Files */
?>
<?php
$_heigth = 75;
$_width = 100;
?>
<?php if ($block->getFilesCount() > 0): ?>
    <?php foreach ($block->getFiles() as $file): ?>
        <div data-row="file" class="filecnt" id="<?= $block->escapeHtmlAttr($block->getFileId($file)) ?>">
            <p class="nm" style="height:<?= $block->escapeHtmlAttr($_heigth) ?>px;width:<?= $block->escapeHtmlAttr($_width) ?>px;">
                <?php if ($block->getFileThumbUrl($file)): ?>
                    <img src="<?= $block->escapeHtmlAttr($block->getFileThumbUrl($file)) ?>" alt="<?= $block->escapeHtmlAttr($block->getFileEnding($file)) ?>"/>
                <?php else: ?>
                    <div><?php echo $block->getFileEnding($file); ?></div>
                <?php endif; ?>
            </p>
            <small><?= $block->escapeHtml($block->getFileShortName($file)) ?></small>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <div class="empty"><?= $block->escapeHtml(__('No files found')) ?></div>
<?php endif; ?>
