<?php
$flyUrl = $this->getUrl('flagbit_flysystem/filesystem/index',
    [
        'target_element_id' => 'flysystem_image_path',
        'type' => 'file',
        'identifier' => 'flagbit_filemanager'
    ]);
?>

<div id="flagbit-flysystem-modal">
    <input class="admin__control-text"
           type="hidden"
           name="product[flysystem_image]"
           id="flysystem_image_path" />
    <button id="flysystem_image_path_button"
            type="button"
            onclick="MediabrowserUtility.openDialog(this.getAttribute('data-url'))"
            data-index="flagbit_flysystem_modal"
            data-url="<?= $flyUrl; ?>">
        <span>Manage Files</span>
    </button>
</div>