<?php
// @codingStandardsIgnoreFile

 /** @var $block \Flagbit\Flysystem\Block\Adminhtml\Filesystem\Content */
?>

<div class="flysystem-browser" data-mage-init='{"mediabrowser": <?= $block->escapeHtml($block->getFilebrowserSetupObject()) ?>}'>
    <div class="side-col"><?= $block->getChildHtml('flagbit_flysystem.tree') ?></div>
    <div class="main-col">
        <div class="insert-title" id="content_header">
            <div class="insert-title-inner">
                <div class="insert-actions">
                    <?= $block->getButtonsHtml() ?>
                </div>
                <div class="title"><?= $block->escapeHtml($block->getHeaderText()) ?></div>
            </div>
        </div>
        <div id="error-message" data-action="show-error"></div>
        <div id="contents-uploader" class="contents-uploader"><?= $block->getChildHtml('flagbit_flysystem.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
